numbers = input().split()
snum = ' '.join(numbers)
for i in range(len(numbers)):
    numbers[i] = int(numbers[i])
numMax, numMin = max(numbers), min(numbers)
iMax, iMin = numbers.index(numMax), numbers.index(numMin) 
numbers.insert(iMax, numMin)
item = numbers.pop(iMax+1)
numbers.insert(iMin, numMax)
item = numbers.pop(iMin+1)
print(*numbers)
